name: Docker Compose Actions Workflow
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with gcc 7
        run: docker-compose run --rm build_gcc_7
      - name: Build with gcc 8
        run: docker-compose run --rm build_gcc_8
      - name: Build with gcc 9
        run: docker-compose run --rm build_gcc_9
      - name: Build with gcc 10
        run: docker-compose run --rm build_gcc_10
      - name: Build with gcc 11
        run: docker-compose run --rm build_gcc_11
      - name: Build with gcc 12
        run: docker-compose run --rm build_gcc_12